### ISSUE TITLE
Is `return` a keyword?

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#12]
I think it would make sense to have `return` as an enum in `KeywordAST` instead of having separate `ReturnExprAST`.
Who doesn't agree? :)

**Comment by rafalcieslak** [comment]
I would say quite the contrary - I believe `break` and `continue` statements should have their own subclasses in the AST. The `KeywordAST` is a bit confusing, because it is meant to serve only one-keyword-statement-expressions. Note that `for` or `fun` are also keywords, but _not_ keywords in the sense of `KeywordAST`. Which is a processed and codegenned as a `switch(keyword)` anyway.

This really boils down to where we want to draw the line between the AST and it's content layout.

Maybe a reasonable compromise would be to rename `KeywordAST` to `LoopControlStatementAST`, and leave `return` as it is.
