### ISSUE TITLE
Make RTTI available

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#17]
We use things like `typeinfo` or `dynamic_cast` around so we need RTTI enabled. However, when commenting out `-fno-rtti` in `CMakeLists.txt`, we get (as of https://github.com/rafalcieslak/CCoscope/commit/dd59ee54d5b5e5c8f229d273244a58ed4ffff267 )

```
CMakeFiles/CCoscope.dir/codegencontext.cpp.o:(.rodata._ZTIN4llvm8FCmpInstE[_ZTIN4llvm8FCmpInstE]+0x10): undefined reference to `typeinfo for llvm::CmpInst'
CMakeFiles/CCoscope.dir/codegencontext.cpp.o:(.rodata._ZTIN4llvm8ICmpInstE[_ZTIN4llvm8ICmpInstE]+0x10): undefined reference to `typeinfo for llvm::CmpInst'
CMakeFiles/CCoscope.dir/codegencontext.cpp.o:(.rodata._ZTIN4llvm17GetElementPtrInstE[_ZTIN4llvm17GetElementPtrInstE]+0x10): undefined reference to `typeinfo for llvm::Instruction'
```

I think we need to either pass some additional flags to clang/llvm or rebuild it somehow so that it doesn't complain when using rtti. I don't believe people discard this feature when using llvm -- there must be a way to do that. Question is - how? :)

**Comment by rafalcieslak** [comment]
Ouch. We shouldn't have stumbled on this problem. Yes, it should be solvable by rebuilding the llvm library so that is exposes RTTI, but that would mean everyone who wishes to use our compiler needs to rebuild llvm, as packaged versions never expose type info. We might also run into some ABI compatibility problems when a packaged version is compiled with a different compiler than our sources...

But I believe we should not need RTTI for llvm types. As far as I currently understand your refactoring, we would only need it for our own types. What is the exact context where we need type information for `llvm::CmpInst` or `llvm::Instruction`?

(By the way, an ultimate solution would be to wait for https://isocpp.org/files/papers/n4028.pdf or like).

**Comment by socumbersome** [comment]
> What is the exact context where we need type information for llvm::CmpInst or llvm::Instruction?

Good question -- I'm trying to track it down...

**Comment by rafalcieslak** [comment]
I can't reproduce this. At dd59ee5 all TUs compile sucessfully, and the linker fails because of

```
multiple definition of `ccoscope::ExprAST::equal(ccoscope::ExprAST const&) const'
```

and

```
undefined reference to `ccoscope::str2type(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
```

but it does not mention any typeinfo missing. So apparently the version of llvm that I use provides rtti. Now it turns out I am still running llvm3.6 (and the `master` branch compiles perfectly!) that is provided in Ubuntu repositories.

If you wish to rebuild your copy of LLVM with RTTI enabled, do consult this page: http://llvm.org/docs/CMake.html  (search for LLVM_ENABLE_RTTI, apparently it's off by default).

**Comment by socumbersome** [comment]
After rebuilding LLVM I don't get these errors, so I deem the issue closed.
