### ISSUE TITLE
Runtime library, mix of C and C++

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#35]
I don't understand what exactly is going on in `common/common_types.h` -- why are we taking care of whether this unit is compiled by C or C++ compiler when defining `struct __cco_complex`, and then blissfully use templates below? It seems to me that, because we are using magic from LLVM like `TypeBuilder`, we are convicted to using C++ only. Is that correct?

**Comment by socumbersome** [comment]
Ok, I learnt a bit about linking by tinkering. On `string_support` branch, I decided to dispel the illusion that `libcco` is a C library and as of (386f73a317b201f76a48279b835e69650ffc5f94) everything seems to work.
Now, do I understand it correctly that initially `libcco` was more C-like (even though not fully-C) because of portability issues? And is it correct that the version I created at linked commit is as much portable as the old one? If so, what is a real merit of having more C-like version?

**Comment by rafalcieslak** [comment]
The runtime library never used any C++, it was written entirely in C. This is because we intend to statically link the library with code generated by our compiler. Restricting ourselves to pure C within the library has, at least, these following benefits:
- It will be always simple to evaluate and investigate the compiled version of the library, as - due to it's simplicity - C source code always clearly corresponds to the compile machine code. Note that before we implemented the runtime library, we were manually composing LLVM IR code snippets - and this is what we actually want to use, but since it's difficult to write IR, I offered a switch to C, since writing in C one can easily understand what binary code will be generated after compiling the library.
- If we choose to use pure C, we'll never incautiously start using any complex C++ features, like exceptions, complex types, RTTI. And we can't use such features, because functions compiled by CCO won't provide support for them - and even if they did, they would need to stay compatible with the implementation used by the compiler we use for compiling the runtime library. So even if we were to write the runtime library in C++, we can't use most of the goodies C++ provides.
- Furthermore, I don't really like the idea of calling functions from C++ libraries, _including_ the standard C++ library. If we do, then binaries compiled by CCO will either:
  - dynamically link to c++ stdlib, which is in no way elegant for a custom language (unless we are actually implementing C++ compiler, but that changes the story entirely)
  - include c++ stdlib statically linked, but that _massively_ increases binary size, because even simple functions from C++ std library have lots of entangled dependencies.
  
  What is more, we would need to carefully choose functions so that they wouldn't break point 2 above.
  
  For exactly the same reason would not like an implementation of `__cco_string` that would use an `std::string` underneath. Sure, it makes runtime implementation simpler, because we would just need to wrap stdlib functions into our custom interface. But it would become really difficult to debug CCO generated binaries, as that would require clear understanding of the particular `std::string` implementation that is used. It would make us depend on that library. And it would cause tons of trouble if a string method would happen to throw an exception.

So to put it short, the runtime library has to be (and can be!) very limited and very simple. Which is why I consider C a better choice than C++ for this particular purpose.

As a side note, generally libraries are written in C (unless they are meant to be used for a particular language, in which case they are written in the same language), mostly because of the same reasons as I listed above, plus the advantage of portability.

**Comment by socumbersome** [comment]
I understand your points and yes, they convince me : )
But I'm still lacking the understanding of how `TypeBuilder` comes into play (which is a C++ thingy). Is it legitimate to say that `common/common_types.h` is a part of our runtime library? I guess so... and if so, inevitably, the whole thing becomes a C++ library (but with a very restricted set of C++ features used inside).
If you have already included the answer to this doubt, then I'm sorry and please reiterate :)

**Comment by rafalcieslak** [comment]
The file `common/common_types.h` serves multiple purposes. I suppose it would be more clear if it was split into three files:
1. One file would only contain the definition of `struct __cco_complex` (and other complex types that are not yet implemented) and nothing else. That would be a C header file. This file would be included in all `libcco` runtime library source files. The purpose of this file would be to define the layout of our custom data structures, so that runtime library implementation can access structure's fields.
2. The second file would have the same contents as 1, but it would be wrapped into an `extern "C"` scope. This would be a C++ header file, included e.g. by `codegencontext.cpp`, and used by `CodegenContext::PrepareStdFunctionPrototypes_()`, which creates the prototypes of runtime library functions so that we can refer to these functions from within LLVM representation. In order to correctly define these prototypes, we need to know how exactly `__cco_complex` looks like, and that's why the compiler needs to include a header that defines our custom structure layout.
3. The third file would provide a compatibility wrapper for interacting with LLVM using our file. It would be a C++ header, and would be included by various source files, e.g. `codegencontext.cpp`. This file would contain `llvm::StructType* __cco_type_to_LLVM<__cco_complex>()` template specialization, which is a useful function for converting types as we call them into types as LLVM represents them on runtime. It would also contain `llvm::TypeBuilder<__cco_complex>` class specialization - this class is used by LLVM as a convenience utility which translates compile-time types into runtime LLVM types representation (thanks to this specialization, we can write `llvm::TypeBuilder<__cco_complex(__cco_complex,int)>::get()` and it will return the correct `llvm::FunctionType`). So just a bunch of utility converters, that translate C++ typenames into LLVM representation.

Note that it is of uttermost significance that the definition of data layout in our custom structures (e.g. `__cco_complex`) needs to stay consistent between these three files. In order to simplify maintenance, I merged these three files together into one (`common_types.h`), so that these three definitions stay close together (and, in fact, 1. and 2. are merged into the same source).

Now the same file `common_types.h` is included from both the runtime library, and various compiler sources. In the first case, it gets compiled by a C compiler, and thus the preprocessor variable `__cplusplus` is not defined. Due to `#ifdef`s in this file, it will look exactly as 1. for a C compiler. In the second case, this file is treated as C++ file, and thus that preprocesor variable is defined. Thus for a C++ compiler, this file looks like 2. + 3.

Therefore this file is neither part of the runtime library nor the compiler, it is a part of an external types definition, which is used by both components of our source code, shared as a common file.

And it doesn't cause the runtime library to become a C++ library, because all C++ source within `common_types.h` is disabled via `#ifdef`s during compilation of the runtime library.

Does it make more sense now? :-)

**Comment by socumbersome** [comment]
This is a great explanation, thanks!
So I'm closing this issue and promise never to try make `libcco` a C++ library again : )
